.\" Manpage for BareCam
.\" Contact jmedved@jmedved.com to correct errors or typos.
.TH BARECAM 1 "CURR_DATE" "MAJOR.MINOR.PATCH" "BareCam Manual"


.SH NAME
BareCam - simplest full-screen camera


.SH SYNOPSIS

.ad l
\fBbarecam\fP


.SH DESCRIPTION
Application will show your webcam output in the full screen.


.SH SHORTCUTS

.TP
\fBEscape\fP
Exit application

.TP
\fBEnter\fP
Show menu

.TP
\fBSpace\fP
Switch camera


.SH SETTINGS

Settings are stored in \fB~/.config/barecam.conf\fP when application is
installed and next to executable in \fB.barecam\fP if run directly. It is
recommended to change settings from application menu but they can also be
changed directly.

.TP
\fBDisableScreensaver\fP
Controls if screensaver will be disabled while application is running. Valid
values are \fBtrue\fP and \fBfalse\fP.
    DisableScreensaver: true

.TP
\fBUseEscapeToExit\fP
Controls if escape key will be used to exit application. Valid values are
\fBtrue\fP and \fBfalse\fP.
    UseEscapeToExit: true


.SH AUTHOR

Josip Medved <jmedved@jmedved.com>
